version: "3.7"
services:
  postgres_cadastro:
    container_name: postgres_cadastro_brunglas
    image: postgres:13.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
